### PR TITLE
[tests] verify `$DOTNET_MODIFIABLE_ASSEMBLIES` is set

### PR DESCRIPTION
**Pull request by jonathanpeppers**

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Ok, test catches the bug, yay!

image

Now I'll run w/ monodroid changes in:
* https://github.com/xamarin/monodroid/pull/1555

**Comment by jonathanpeppers** [comment]
Ok, latest change worked:

image

So, taking this out of draft:
* https://github.com/xamarin/monodroid/pull/1555

**Comment by dellis1972** [comment]
Merged, just need to bump this PR and take it out of draft

**Comment by jonathanpeppers** [comment]
For the commit message:

```
Bump to xamarin/monodroid/main@

Changes: https://github.com/xamarin/monodroid/compare/87e386cb...62976287

* [Debugging.Tasks] Update System.Text.Json to 8.0.5

* [ci] Use latest macOS-14 image

* [Debugging.Tasks] Resolve build warnings

* Bump to xamarin/androidtools/main@24626, xamarin/android-sdk-installer/main@5ed12, dotnet/android/main@ac8bf

* [tools/msbuild] fix padding on longest fast deployed env var
```

**Review by dellis1972 — APPROVED** [review]

**Comment by dellis1972** [comment]
Looks ok, I re-ran the failing test though.

**Pull request merged**
