### PR TITLE
[release/8.0.4xx] Backport maestro and artifact drop infra improvements

### PR DESCRIPTION
**Pull request by pjcollins**
Backports the following maestro and artifact storage changes:

https://github.com/dotnet/android/commit/bbac9fe4ce1014f02c6f9933a13485dc20089a9d
https://github.com/dotnet/android/commit/f834b5531a8c2d4ef02084f553712392ff2c48a5
https://github.com/dotnet/android/commit/9ba9efa964ddf358d48fd27e188e508b2b3c836e
https://github.com/dotnet/android/commit/55c2dd8b275485905b18360fb3aca622411f5ee6
https://github.com/dotnet/android/commit/d050fda83a61bb7cd31e0a0686e9047cb01f924d
https://github.com/dotnet/android/commit/8a85c109d0d0a56a4a36cc1be2e645579ca9b5fe

### CODE REVIEW

**Comment by pjcollins** [comment]
Test build here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10048529&view=results

**Review by jonathanpeppers — COMMENTED** [review]
Some reason the build timed out, I restarted it.

**Comment by pjcollins** [comment]
Oops missed a commit, new test build:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=10054781&view=results

**Review by jonathanpeppers — APPROVED** [review]
This one is still ongoing:

image

But if that one works, I think we can probably merge. 👍

**Pull request merged**
