### PR TITLE
Bump to xamarin/monodroid@1a9ee373

### PR DESCRIPTION
**Pull request by pjcollins**
Changes: https://github.com/xamarin/monodroid/compare/e6a7cf474abe406f85aac55531fc46ead8f3f7d8...1a9ee3733285238e0630f230c383cf3df1a6736d

 * xamarin/monodroid@1a9ee37: Remove jar2xml and xamarin-analysis submodules
 * xamarin/monodroid@5d89b0b: Add Xamarin.Installer.Common.props
 * xamarin/monodroid@b632d51: Fix xamarin.sync stdin hang

Replaces Xamarin.Android.Tools.Versions.props with Xamarin.Installer.Common.props.

### CODE REVIEW

**Review by jonathanpeppers — COMMENTED** [review]
@pjcollins we might have to delete xamarin-analysis on the monodroid/release/8.0.4xx branch:
```
Failed to clone 'external/xamarin-analysis'. Retry scheduled
Skipping submodule 'external/xamarin-android'
```

**Comment by pjcollins** [comment]
> @pjcollins we might have to delete xamarin-analysis on the monodroid/release/8.0.4xx branch:
> 
> ```
> Failed to clone 'external/xamarin-analysis'. Retry scheduled
> Skipping submodule 'external/xamarin-android'
> ```

I'm not sure why the clone also recently started failing, it seems like the archive should still be accessible... I've backported the xamarin-analysis removal here though:
https://github.com/xamarin/monodroid/pull/1545

**Review by dellis1972 — APPROVED** [review]

**Comment by pjcollins** [comment]
I think the `CustomDesignerTargetSetupDependenciesForDesigner` failure here is expected

**Pull request merged**
