### PR TITLE
[release/8.0.4xx] Bump to dotnet/android-tools@f53106a1

### PR DESCRIPTION
**Pull request by pjcollins**
With https://github.com/dotnet/android-tools/pull/220, we now need to set `$(_IncludeMicrosoftBuildPackage)` for projects that need a `Microsoft.Build` reference.

Changes: https://github.com/dotnet/android-tools/compare/d50747cbddf6ab3e2151fc2ae3e3af76edb4fd72...f53106a126b0e2f7f34802de5e1f99be4c34ce54

  * dotnet/android-tools@f53106a: Bump to dotnet/msbuild@10fbfbf2
  * dotnet/android-tools@a2e146d: Bump to dotnet/msbuild/v17.9.5@33de0b22
  * dotnet/android-tools@1818d59: Bump LibZipSharp and Xamarin.Build.AsyncTask
  * dotnet/android-tools@75f79e7: Bump LibZipSharp to 3.1.1
  * dotnet/android-tools@b1f795e: [MSBuildReferences.projitems] Require opt-in to use `Microsoft.Build`

Changes: https://github.com/xamarin/monodroid/compare/b753d75f846b76cabb3b65b52ac12c4a83c07a13...99627fea9cf2ce9ca59fa571ea5640f8eb4a9c59

  * xamarin/monodroid@99627fe: [release/8.0.4xx] Bump android-sdk-installer, androidtools

### CODE REVIEW

**Review by dellis1972 — APPROVED** [review]

**Comment by pjcollins** [comment]
The failures in `CustomDesignerTargetSetupDependenciesForDesigner` and `TestResolveToolsExists` are already present on the branch, I think this should be good to go

**Comment by dellis1972** [comment]
Do we need to do the old `androidtools` as well (via monodroid). Looking at the commits we are at `[xamarin-android-tools @ d50747c](https://github.com/xamarin/xamarin-android-tools/tree/d50747cbddf6ab3e2151fc2ae3e3af76edb4fd72)` See https://github.com/xamarin/androidtools/tree/6ba69ad1c817a4d4bd5004339f4440dd9885ee4b/external

**Review by jonathanpeppers — APPROVED** [review]

**Comment by pjcollins** [comment]
> Do we need to do the old `androidtools` as well (via monodroid). Looking at the commits we are at [xamarin-android-tools@d50747c](https://github.com/xamarin/xamarin-android-tools/tree/d50747cbddf6ab3e2151fc2ae3e3af76edb4fd72) See https://github.com/xamarin/androidtools/tree/6ba69ad1c817a4d4bd5004339f4440dd9885ee4b/external

Yes sorry good catch! it looks like all of monodroids dependencies are up to date but we were missing a couple of bumps in monodroid. I've set that up here https://github.com/xamarin/monodroid/pull/1559 and we can include once merged.

**Review by dellis1972 — APPROVED** [review]

**Review by jonathanpeppers — APPROVED** [review]
I reran some of the failures to see if it can be slightly greener.

We can ignore the `CustomDesignerTargetSetupDependenciesForDesigner` test for sure.

**Comment by pjcollins** [comment]
Thanks, we're down to the two failures in `CustomDesignerTargetSetupDependenciesForDesigner` and `TestResolveToolsExists` already present on the branch, should be good

**Pull request merged**
